---
title: "UpCH4: Code Notebook for Random Forest Model Dev. and Eval."
author: "Gavin McNicol"
date: "2023-05-24"
output::tuft_html:
  css: notebook.css
  tuft_variant: "envisioned"
  highlight: pygments
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

Code for predictive model development and evaluation for upscaling eddy covariance methane flux data from sites to the globe. The code takes pre-processed weekly mean eddy covariance flux tower from FLUXNET-CH4 v1.0 [(Delwiche et al. 2021)](http://dx.doi.org/10.5194/essd-13-3607-2021) and static and dynamic geospatial predictor datasets as input for a random forest model training pipeline, and outputs:

  1) a best-predictor set using forward spatial feature selection
  2) spatial cross validation metrics of model performance
  3) variable importance rankings

The final three sections output:

  4) simulated training datasets from Monte Carlo to propagate uncertainties
  5) representativeness products (dissimilarity and constituency maps)
  6) globally upscaled product evaluations
  
Manuscript Reference: *McNicol, G. Fluet-Chouinard, E. et al. Upscaling wetland methane emissions from the FLUXNET-CH4 eddy covariance network (UpCH4 v1.0): Model development, network assessment, and budget comparison. AGU Advances, Accepted, May 2023*



